kungfu_blog/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),

	url(r'^post/', include(('mypost.urls', 'mypost'), namespace='mypost')),
	url(r'^profile/', include(('myprofile.urls', 'myprofile'), namespace='myprofile')),
	url(r'^account/', include(('myaccount.urls', 'myaccount'), namespace='myaccount')),

	url(r'^api/v1/post/', include(('restpost.urls', 'restpost'), namespace='restpost')),
	url(r'^api/v1/profile/', include(('restprofile.urls', 'restprofile'), namespace='restprofile')),
	url(r'^api/v1/account/', include(('restaccount.urls', 'restprofile'), namespace='restaccount')),
]

myaccount/urls.py
from django.urls import path

from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
	url(r'^login/$', auth_views.LoginView.as_view(template_name='myaccount/login.html'), name='login'),
	url(r'^logout/$', auth_views.LogoutView.as_view(template_name='myaccount/logout.html'), name='logout'),
	url(r'^register/$', views.register, name='register'),
]

mypost/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^add', views.add, name='add'),
	url(r'^list', views.all_posts, name='list'),
	url(r'^(?P<pk>\d+)/$', views.show_post, name='post-show'),
	url(r'^category/(?P<pk>\d+)/$', views.list_category, name='category'),
]

mypost/models.py
from django.db import models


class Post(models.Model):
	timestamp = models.DateTimeField(auto_now=False, auto_now_add = True)
	category = models.IntegerField(default=0,blank=True)
	title = models.CharField(max_length=400, default=0)
	text = models.CharField(max_length=400, default=0)
	author = models.IntegerField(default=0)
	def __str__(self):
		return self.title


class Category(models.Model):
	id_category = models.IntegerField(default=0)
	name = models.CharField(max_length=400, default=0)

	def __str__(self):
		return self.name

mypost/forms.py
from django import forms
from mypost.models import Post


class AddForm(forms.ModelForm):
	class Meta:
		model = Post
		exclude = ('author',)

class ListForm(forms.ModelForm):
	class Meta:
		model = Post
		exclude = [""]

mypost/views.py
from django.shortcuts import render
from .forms import AddForm
from .forms import ListForm
from django.shortcuts import render

from mypost.models import Post
from mypost.models import Category

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from django.core.paginator import Paginator

def add(request):
	form = AddForm(request.POST)
	post_category = Category.objects.all()
	if request.method == 'POST':
		print(form.errors)
		if form.is_valid():
			post_saved = form.save(commit=False)
			post_saved.author = request.user.id
			form.save()
	return render(request, 'add.html', {'form': form, 'post_category': post_category})


def all_posts(request):

	form = ListForm(request.POST)
	posts = Post.objects.all().order_by('-id')
	categoty_search = Category.objects.all()

	if request.method == 'POST':
		category_id = request.POST.get('category_id_f')
		posts = Post.objects.filter(category=category_id).order_by('-id')
	
	paginator = Paginator(posts, 10)
	page = request.GET.get('page')
    
	posts = paginator.get_page(page)

	context_posts = {
		'posts': posts,
		'categoty_search': categoty_search,
	}

	return render(request, 'all_posts.html', context_posts)



def list_category(request, pk:None):

	form = ListForm(request.POST)
	posts = Post.objects.filter(category=pk).order_by('-id')
	categoty_search = Category.objects.all()

	if request.method == 'POST':
		category_id = request.POST.get('brand_id_f')
		posts = Post.objects.filter(category=category_id_f).order_by('-id')
	
	paginator = Paginator(posts, 10)
	page = request.GET.get('page')
    
	posts = paginator.get_page(page)

	context_posts = {
		'posts': posts,
		'categoty_search': categoty_search,
	}

	return render(request, 'all_posts.html', context_posts)



def show_post(request, pk):
	post = get_object_or_404(Post,pk=pk)
	brand = Category.objects.get(id=post.category)
	return render(request, 'post.html', {'post':post, 'brand':brand})

mypost/templates/add.html
{% extends "base.html" %}
{% block head_title %}Add Post{% endblock %}
{% block content %}


<form action="" method="post">
{% csrf_token %}
Title
<br>
<input type="text" name="title" value="Name Post">
<hr>

Text
<br>
<input type="text" name="text" value="Text Post">
<hr>


Category
<br>
<select name="category">
    {% for i in post_category %}
    <option value="{{ i.id_category }}">{{ i.name }}</option>
    {% endfor %}
</select>
<hr>

<input type="submit" value="Add" />
</form>


{% endblock %}

mypost/templates/all_posts.html
{% extends "base.html" %}
{% block content %}
<form action="" method="post">
{% csrf_token %}
<div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
            <div class="panel-heading">Category</div>
            <div class="panel-body">
                <select name="category_id_f">
                    {% for i in categoty_search %}
                    <option 
                        value="{{ i.id }}">
                        {{ i.name }}
                    </option>
                    {% endfor %}
                </select>
                <hr>
        
          </div>
        </div>
    </div>
  </div>

<input type="submit" value="Search" />
</form>
<hr>

{% for post in posts %}

    Id: <a href="{% url 'mypost:post-show' post.id %}">{{ post.id }}</a>
    <br>
    Title: {{ post.title }}
    <hr>
    <br>

{% endfor %}




{% if posts.has_other_pages %}
    <ul class="pagination">
        {% if posts.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.previous_page_number }}">&laquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">&laquo;</a>
            </li>
        {% endif %}
        {% for i in posts.paginator.page_range %}
            {% if posts.number == i %}
                <li class="page-item active">
                    <a class="page-link">{{ i }} <span class="sr-only">(current)</span></a>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if posts.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.next_page_number }}">&raquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">&raquo;</a>
            </li>
        {% endif %}
    </ul>
{% endif %}

<hr>



{% endblock %}

mypost/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" >
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> -->


    <!-- <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" /> <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"> </script> <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>


  </head>
  <body>

<ul class="nav justify-content-center">
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'mypost:list'%}">Kung Fu Blog</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'mypost:category' 1 %}">Linux</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'mypost:category' 2 %}">MacOS</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'mypost:category' 3 %}">Windows</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'mypost:category' 4 %}">MsDOS</a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{% url 'myaccount:register'%}">Register</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'myaccount:login'%}">Login</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'myaccount:logout'%}">Logout</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'myprofile:list'%}">Profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'mypost:add'%}">ADD</a>
  </li>


</ul>
<hr>

    <div class="container">
    {% block body %}

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
    <hr>
    {% endif %}

    


    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}

    </div>
  </body>
</html>

mypost/templates/post.html
{% extends "base.html" %}
{% block head_title %}{{ post.title }}{% endblock %}
	{% block content %}
	
		<div class="container">
			id:<br>
			<b>{{ post.id }}</b>
			<br>
			Title:<br>
			<b>{{ post.title }}</b>
			<br>
			Text:
			<br>
			<b>{{ post.text }}</b>
			<br>
			Category:
			<br>
			<b>{{ brand.name }}</b>
		</div>

	{% endblock %}