kungfu_blog/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),

	url(r'^post/', include(('mypost.urls', 'mypost'), namespace='mypost')),
	url(r'^profile/', include(('myprofile.urls', 'myprofile'), namespace='myprofile')),
	url(r'^account/', include(('myaccount.urls', 'myaccount'), namespace='myaccount')),

	url(r'^api/v1/post/', include(('restpost.urls', 'restpost'), namespace='restpost')),
	url(r'^api/v1/profile/', include(('restprofile.urls', 'restprofile'), namespace='restprofile')),
	url(r'^api/v1/account/', include(('restaccount.urls', 'restprofile'), namespace='restaccount')),
]

mypost/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^add', views.add, name='add'),
	url(r'^list', views.all_posts, name='list'),
	url(r'^(?P<pk>\d+)/$', views.show_post, name='post-show'),
	url(r'^category/(?P<pk>\d+)/$', views.list_category, name='category'),
]

myprofile/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^list', views.all_posts, name='list'),
	url(r'^update/(?P<pk>\d+)/$', views.update_post, name='update'),
	url(r'^delete/(?P<pk>\d+)/$', views.delete_post, name='delete'),
]

myprofile/models.py
from django.db import models

# Create your models here.

myprofile/forms.py
from django import forms
from mypost.models import Post


class ListForm(forms.ModelForm):
	class Meta:
		model = Post
		exclude = [""]

class UpdateForm(forms.ModelForm):
	class Meta:
		model = Post
		exclude = ('author',)

myprofile/views.py
from django.shortcuts import render, redirect
from .forms import ListForm
from django.shortcuts import render

from mypost.models import Post
from mypost.models import Category
from django.core.paginator import Paginator

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import UpdateForm


def all_posts(request):

	user = request.user.id
	form = ListForm(request.POST)
	posts = Post.objects.filter(author=user).order_by('-id')
	category_search = Category.objects.all()

	if request.method == 'POST':
		category_id = request.POST.get('category_id_f')
		posts = Post.objects.filter(category=category_id, author = user).order_by('-id')
	
	paginator = Paginator(posts, 10)
	page = request.GET.get('page')
    
	posts = paginator.get_page(page)

	context_posts = {
		'posts': posts,
		'category_search': category_search,
	}

	return render(request, 'myprofile/all_posts.html', context_posts)





def update_post(request, pk):
	post = Post.objects.get(pk=pk)

	form = UpdateForm(request.POST, instance=post)
	all_category = Category.objects.all()
	if request.method == 'POST':
		print(form.errors)
		if form.is_valid():
			form.save()
	return render(request, 'myprofile/update.html', {'form': form, 'all_category': all_category, 'post': post})


def delete_post(request, pk):
	post = get_object_or_404(Post,pk=pk)
	if request.method == 'POST':
		post.delete()
		return redirect('myprofile:list')
	context = {
		"object": post
	}
	return render(request, 'myprofile/delete.html', context)

myprofile/templates/myprofile/all_posts.html
{% extends "base.html" %}
{% block content %}
<form action="" method="post">
{% csrf_token %}
<div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
            <div class="panel-heading">Category</div>
            <div class="panel-body">
                <select name="category_id_f">
                    {% for i in category_search %}
                    <option 
                        value="{{ i.id }}">
                        {{ i.name }}
                    </option>
                    {% endfor %}
                </select>
                <hr>
        
          </div>
        </div>
    </div>
  </div>

<input type="submit" value="Search" />
</form>
<hr>

{% for post in posts %}

    Id: <a href="">{{ post.id }}</a>
    <br>
    Title: {{ post.title }}
    <br>
    <a href="{% url 'myprofile:update' post.id %}">Update</a>
    <br>
    <a href="{% url 'myprofile:delete' post.id %}">Delete</a>
    <hr>

{% endfor %}






{% if posts.has_other_pages %}
    <ul class="pagination">
        {% if posts.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.previous_page_number }}">&laquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">&laquo;</a>
            </li>
        {% endif %}
        {% for i in posts.paginator.page_range %}
            {% if posts.number == i %}
                <li class="page-item active">
                    <a class="page-link">{{ i }} <span class="sr-only">(current)</span></a>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if posts.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.next_page_number }}">&raquo;</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">&raquo;</a>
            </li>
        {% endif %}
    </ul>
{% endif %}

<hr>



{% endblock %}

myprofile/templates/myprofile/delete.html
{% extends 'base.html' %}

{% block content %}


<form action='.' method='POST'>{% csrf_token %}
    <h1>Do you want to delete the post "{{ object.title }}"?</h1>
    <p><input type='submit' value='Yes' />  <a href='../'>Cancel</a></p>

</form>




{% endblock %}

myprofile/templates/myprofile/update.html
{% extends "base.html" %}
{% block head_title %}Update{% endblock %}
{% block content %}


<form action="" method="post">
{% csrf_token %}
Title
<br>
<input type="text" name="title" value="{{ post.title }}">
<hr>

Text
<br>
<input type="text" name="text" value="{{ post.text }}">
<hr>

Category
<br>
<select name="category">
    {% for i in all_category %}
    <option value="{{ i.id_category }}">{{ i.name }}</option>
    {% endfor %}
</select>
<hr>

<input type="submit" value="Update" />
</form>


{% endblock %}